const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={conversation:null,collections:[],selected:new Set(),authenticated:false,poll:null};
const reviewLabel='回查原文';
async function api(url,opt={}){const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||d.error?.error_code||d.detail?.message||d.detail?.code||d.detail||`HTTP ${r.status}`);return d}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function textDialog(title,value=''){return new Promise(resolve=>{const finish=result=>{$('#modal').classList.add('hidden');$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');resolve(result)};$('#modalBody').innerHTML=`<div class="dialog-form"><h2>${esc(title)}</h2><input id="dialogValue" type="text" value="${esc(value)}"><div><button id="dialogCancel">取消</button> <button id="dialogConfirm" class="primary">确定</button></div></div>`;$('#modal').classList.remove('hidden');$('#modalClose').onclick=()=>finish(null);$('#dialogCancel').onclick=()=>finish(null);$('#dialogConfirm').onclick=()=>finish($('#dialogValue').value.trim()||null);$('#dialogValue').onkeydown=e=>{if(e.key==='Enter')$('#dialogConfirm').click()};$('#dialogValue').focus();$('#dialogValue').select()})}
function confirmDialog(message){return new Promise(resolve=>{const finish=result=>{$('#modal').classList.add('hidden');$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');resolve(result)};$('#modalBody').innerHTML=`<div class="dialog-form"><h2>确认操作</h2><p>${esc(message)}</p><div><button id="dialogCancel">取消</button> <button id="dialogConfirm" class="danger">确认删除</button></div></div>`;$('#modal').classList.remove('hidden');$('#modalClose').onclick=()=>finish(false);$('#dialogCancel').onclick=()=>finish(false);$('#dialogConfirm').onclick=()=>finish(true)})}
function sourceLabel(type){return type==='private'?'我的文献':type==='temporary'?'临时资料':'官方库'}
function formatTime(value){if(!value)return'';return new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
function renderScopes(){const chosen=state.collections.filter(x=>state.selected.has(x.collection_id));const labels=[];if($('#useOfficial').checked)labels.push('官方库');chosen.forEach(x=>labels.push(x.name));if(state.conversation)labels.push('本会话临时资料');$('#scopeTags').innerHTML=labels.map(x=>`<span>${esc(x)}</span>`).join('');$('#scopeSummary').textContent=labels.join(' · ')||'未选择资料范围'}
async function loadIdentity(){const a=await api('/v1/auth/status');state.authenticated=a.authenticated;$('#loginState').textContent=a.authenticated?`已登录：${a.subject}`:'未登录';return a}
async function loadCollections(){try{const r=await api('/v1/collections');state.collections=r.items.filter(x=>x.scope_type==='private');$('#collectionList').innerHTML=state.collections.length?state.collections.map(x=>`<label class="check"><input type="checkbox" data-collection="${x.collection_id}" ${state.selected.has(x.collection_id)?'checked':''}> <span>${esc(x.name)}</span><button data-manage="${x.collection_id}" title="管理文档">···</button></label>`).join(''):'<p class="muted">还没有私人研究库</p>';$$('[data-collection]').forEach(x=>x.onchange=()=>{x.checked?state.selected.add(x.dataset.collection):state.selected.delete(x.dataset.collection);renderScopes()});$$('[data-manage]').forEach(x=>x.onclick=e=>{e.preventDefault();manageCollection(x.dataset.manage)})}catch{$('#collectionList').innerHTML='<p class="muted">登录后可使用私人研究库</p>'}renderScopes()}
async function loadConversations(){try{const r=await api('/v1/conversations');$('#conversationList').classList.remove('empty');$('#conversationList').innerHTML=r.items.length?r.items.map(x=>`<button data-conversation="${x.conversation_id}" class="${state.conversation===x.conversation_id?'active':''}"><span>${esc(x.title)}</span><small>${formatTime(x.updated_at)}</small></button>`).join(''):'<p class="muted">暂无历史会话</p>';$$('[data-conversation]').forEach(x=>x.onclick=()=>openConversation(x.dataset.conversation))}catch{$('#conversationList').innerHTML='登录后显示历史会话'}}
function renderMessages(items){$('#messages').innerHTML=items.length?items.map(m=>`<article class="message ${m.role}"><div class="role">${m.role==='user'?'你':'PaperTrace'}</div><div>${esc(m.content)}</div>${m.citations?.length?`<div class="citations">${m.citations.map((e,i)=>`<button onclick="showEvidence('${e.evidence_id}',${JSON.stringify(e).replaceAll('"','&quot;')})">[${i+1}] ${sourceLabel(e.source_type)} · ${esc(e.paper_name)} p.${e.page_start}</button>`).join('')}</div>`:''}<time>${formatTime(m.created_at)}</time></article>`).join(''):'<div class="empty-state"><h2>开始新的研究问题</h2></div>';$('#messages').scrollTop=$('#messages').scrollHeight}
async function openConversation(id){try{const c=await api('/v1/conversations/'+id);state.conversation=id;$('#conversationTitle').textContent=c.title;renderMessages(c.messages);await Promise.all([loadConversations(),loadTemporary()]);renderScopes()}catch(e){toast(e.message)}}
async function newConversation(){try{const c=await api('/v1/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'新对话'})});await openConversation(c.conversation_id)}catch(e){toast(e.message)}}
async function loadTemporary(){if(!state.conversation){$('#temporaryFiles').innerHTML='';return}try{const r=await api(`/v1/conversations/${state.conversation}/documents`);$('#temporaryFiles').innerHTML=r.items.map(d=>`<div class="file-row"><span class="status ${esc(d.status)}">${esc(d.status)}</span><b>${esc(d.source_name)}</b><small>${d.expires_at?'到期 '+formatTime(d.expires_at):''}</small><button onclick="promoteDocument('${d.document_id}')">保存到研究库</button><button onclick="deleteDocument('${d.document_id}')">删除</button></div>`).join('');if(r.items.some(x=>['processing','queued'].includes(x.status))){clearTimeout(state.poll);state.poll=setTimeout(loadTemporary,1200)}}catch(e){toast(e.message)}}
$('#askBtn').onclick=async()=>{const q=$('#question').value.trim();if(!q)return;$('#askBtn').disabled=true;$('#composerState').textContent='正在检索并核对证据…';const body={question:q,conversation_id:state.conversation,collection_ids:[...state.selected],include_official:$('#useOfficial').checked};try{const r=await api('/v1/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(state.conversation){await openConversation(state.conversation)}else{renderMessages([{role:'user',content:q},{role:'assistant',content:r.answer,citations:r.evidence}])}if(r.degraded)toast('部分模型不可用，已明确降级')}catch(e){toast(e.message)}finally{$('#askBtn').disabled=false;$('#composerState').textContent='';$('#question').value=''}};
window.showEvidence=async(id,fallback)=>{try{const suffix=state.conversation?`?conversation_id=${encodeURIComponent(state.conversation)}`:'';const e=await api(`/v1/evidence/${id}${suffix}`);$('#evidenceDetail').innerHTML=`<span class="source ${e.scope_type}">${sourceLabel(e.scope_type)}</span><h3>${esc(e.paper_name)}</h3><p class="meta">第 ${e.page_start}${e.page_end!==e.page_start?`–${e.page_end}`:''} 页 · ${esc(e.section_path||'未标注章节')}</p><blockquote>${esc(e.excerpt)}</blockquote><a class="button" href="/v1/documents/${e.document_id}/pdf" target="_blank">打开 PDF（按页定位）</a><p class="muted">当前版本提供页码与 chunk 定位，不声称 bbox 精确高亮。</p>`;$('#evidencePanel').classList.add('open')}catch(e){if(fallback)toast('证据权限或定位已变化');else toast(e.message)}};
window.reviewEvidence=(paper,page,chunk)=>toast(`证据位于第 ${page} 页；请从右侧证据面板回查原文`);
$('#tempUpload').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!state.conversation){e.target.value='';toast('请先新建或打开会话');return}try{const r=await api(`/v1/conversations/${state.conversation}/documents`,{method:'POST',headers:{'X-Filename':encodeURIComponent(f.name),'Content-Type':'application/pdf'},body:f});toast('临时文献已排队解析');await loadTemporary()}catch(err){toast(err.message)}finally{e.target.value=''}};
window.deleteDocument=async id=>{try{await api('/v1/documents/'+id,{method:'DELETE'});toast('文献已删除');await Promise.all([loadTemporary(),loadCollections()])}catch(e){toast(e.message)}};
window.promoteDocument=async id=>{if(!state.collections.length){toast('请先创建私人研究库');return}const target=state.collections[0];try{await api(`/v1/documents/${id}/promote`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({collection_id:target.collection_id})});toast(`已保存到“${target.name}”`)}catch(e){toast(e.message)}};
async function manageCollection(id){const c=state.collections.find(x=>x.collection_id===id);try{const r=await api(`/v1/collections/${id}/documents`);$('#modalBody').innerHTML=`<div class="section-head"><h2>${esc(c.name)}</h2><div><button onclick="renameCollection('${id}')">重命名</button> <button onclick="deleteCollection('${id}')">删除研究库</button></div></div><label class="upload">上传长期 PDF<input id="privateUpload" type="file" accept="application/pdf"></label><div class="file-list">${r.items.length?r.items.map(d=>`<div class="file-row"><span class="status ${esc(d.status)}">${esc(d.status)}</span><b>${esc(d.source_name)}</b><small>${d.page_count} 页</small><button onclick="deleteDocument('${d.document_id}')">删除</button></div>`).join(''):'<p class="muted">库中暂无文献</p>'}</div>`;$('#modal').classList.remove('hidden');$('#privateUpload').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await api(`/v1/collections/${id}/documents`,{method:'POST',headers:{'X-Filename':encodeURIComponent(f.name),'Content-Type':'application/pdf'},body:f});toast('文献已排队处理');$('#modal').classList.add('hidden')}catch(err){toast(err.message)}}}catch(e){toast(e.message)}}
window.renameCollection=async id=>{const current=state.collections.find(x=>x.collection_id===id);const name=await textDialog('新的研究库名称',current?.name||'');if(!name)return;try{await api('/v1/collections/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});await loadCollections();toast('研究库已重命名')}catch(e){toast(e.message)}};
window.deleteCollection=async id=>{if(!await confirmDialog('删除研究库及其中的文献？此操作不可撤销。'))return;try{await api('/v1/collections/'+id,{method:'DELETE'});state.selected.delete(id);await loadCollections();toast('研究库已删除')}catch(e){toast(e.message)}};
$('#manageCollections').onclick=()=>$('#collectionEditor').classList.toggle('hidden');$('#createCollection').onclick=async()=>{const name=$('#collectionName').value.trim();if(!name)return;try{await api('/v1/collections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});$('#collectionName').value='';await loadCollections();toast('研究库已创建')}catch(e){toast(e.message)}};
$('#newConversation').onclick=newConversation;$('#renameConversation').onclick=async()=>{if(!state.conversation)return;const title=await textDialog('新的会话标题',$('#conversationTitle').textContent);if(!title)return;try{await api('/v1/conversations/'+state.conversation,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title})});await openConversation(state.conversation)}catch(e){toast(e.message)}};$('#useOfficial').onchange=renderScopes;$('#closeEvidence').onclick=()=>$('#evidencePanel').classList.remove('open');$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');
$('#adminToggle').onclick=()=>{$('#userWorkspace').classList.add('hidden');$('#adminWorkspace').classList.remove('hidden');loadAdminDocuments();loadRuns()};$('#backToChat').onclick=()=>{$('#adminWorkspace').classList.add('hidden');$('#userWorkspace').classList.remove('hidden')};$$('[data-admin]').forEach(b=>b.onclick=()=>{$$('[data-admin],.admin-view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#admin-'+b.dataset.admin).classList.add('active')});
$('#loginBtn').onclick=async()=>{try{await api('/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});toast('管理员登录成功');await Promise.all([loadIdentity(),loadCollections(),loadConversations(),loadAdminDocuments(),loadRuns()])}catch(e){$('#loginState').textContent=e.message}};
async function loadAdminDocuments(){try{const r=await api('/v1/papers');$('#paperList').classList.remove('empty');$('#paperList').innerHTML=`<table><thead><tr><th>文档</th><th>状态</th><th>页面</th><th>OCR</th><th>操作</th></tr></thead><tbody>${r.items.map(p=>`<tr><td>${esc(p.file_name)}</td><td><span class="status ${p.status}">${esc(p.status)}</span></td><td>${p.page_count}</td><td>${p.ocr_pages}</td><td><button onclick="inspectPaper('${p.paper_id}')">检查</button>${['failed','partial_failed'].includes(p.status)?`<button onclick="retryPaper('${p.paper_id}')">重试</button>`:''}</td></tr>`).join('')}</tbody></table>`}catch(e){$('#paperList').textContent=e.message}}
window.inspectPaper=async id=>{try{const [p,pages,chunks]=await Promise.all([api(`/v1/papers/${id}`),api(`/v1/papers/${id}/pages`),api(`/v1/papers/${id}/chunks?limit=50`)]);$('#documentInspect').innerHTML=`<div class="detail"><h3>${esc(p.file_name)}</h3><div class="split"><div><h4>页面与 OCR</h4>${pages.items.map(x=>`<details><summary>第 ${x.page_number} 页 · ${esc(x.extraction_method)} · ${esc(x.status)}</summary>${x.error_code?`<p class="error">${esc(x.error_code)} · ${esc(x.error_message)}</p>`:''}<p>${esc(x.text)}</p></details>`).join('')}</div><div><h4>Chunks</h4>${chunks.items.map(x=>`<details><summary>p.${x.page_start} · ${esc(x.section_path)} · ${x.token_count} tokens</summary><p>${esc(x.text)}</p></details>`).join('')}</div></div></div>`}catch(e){toast(e.message)}};
window.retryPaper=async id=>{try{await api(`/v1/papers/${id}/retry`,{method:'POST'});toast('已创建安全重试任务')}catch(e){toast(e.message)}};$('#officialUpload').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await api('/v1/uploads',{method:'POST',headers:{'X-Filename':encodeURIComponent(f.name),'Content-Type':'application/pdf'},body:f});toast('官方文档已排队')}catch(err){toast(err.message)}};
$('#retrieveBtn').onclick=async()=>{const q=$('#testQuestion').value.trim();if(!q)return;$('#retrievalResults').innerHTML='<p class="muted">检索中…</p>';try{const r=await api('/v1/retrieve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,top_k:Number($('#testTopK').value)||8,include_official:true})});$('#retrievalResults').innerHTML=r.results.map((x,i)=>`<article class="retrieval"><b>${i+1}. ${esc(x.paper_name)} · p.${x.page_start}</b><span>${Number(x.score).toFixed(5)}</span><p>${esc(x.excerpt)}</p><details><summary>高级排名信息</summary><code>${esc(x.chunk_id)} · ${esc(x.evidence_id)}</code></details></article>`).join('')||'<p class="muted">没有可靠召回结果</p>'}catch(e){toast(e.message)}};
async function loadRuns(){try{const [runs,queries]=await Promise.all([api('/v1/runs'),api('/v1/queries')]);const runRows=runs.items.map(x=>`<tr><td><span class="status ${x.status}">${esc(x.status)}</span></td><td>入库 · ${esc(x.stage||'queued')}</td><td>${formatTime(x.started_at)}</td><td><button onclick="showRun('${x.run_id}')">详情</button></td></tr>`);const queryRows=queries.items.map(x=>`<tr><td><span class="status ${x.status}">${esc(x.status)}</span></td><td>查询 · ${esc(x.answer_mode||'running')}</td><td>${formatTime(x.started_at)}</td><td><button onclick="showQuery('${x.request_id}')">详情</button></td></tr>`);$('#runsList').innerHTML=`<table><thead><tr><th>状态</th><th>类型/阶段</th><th>开始时间</th><th>操作</th></tr></thead><tbody>${[...runRows,...queryRows].join('')}</tbody></table>`}catch(e){$('#runsList').textContent=e.message}}
window.showRun=async id=>{try{const r=await api('/v1/runs/'+id);$('#runDetail').innerHTML=`<div class="detail"><h3>运行详情</h3><p><span class="status ${r.status}">${esc(r.status)}</span> · ${esc(r.kind)} · ${esc(r.stage||'')}</p>${r.error?`<p class="error">${esc(r.error.error_code)} · ${esc(r.error.message)}</p>`:''}<ol>${r.stages.map(s=>`<li><b>${esc(s.stage)}</b> ${esc(s.status)} · ${s.duration_ms??'—'} ms</li>`).join('')}</ol><details><summary>高级：原始 JSON</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details></div>`}catch(e){toast(e.message)}};$('#refreshRuns').onclick=loadRuns;
(async()=>{try{const r=await api('/ready');$('#health').textContent=r.ready?'服务正常':'服务可用 · 部分组件待配置';$('#health').classList.add(r.ready?'ok':'warn')}catch{$('#health').textContent='服务离线'}await loadIdentity().catch(()=>{});await Promise.all([loadCollections(),loadConversations()]);renderScopes()})();
window.showQuery=async id=>{try{const q=await api('/v1/queries/'+id);$('#runDetail').innerHTML=`<div class="detail"><h3>查询详情</h3><p><span class="status ${q.status}">${esc(q.status)}</span> · ${esc(q.answer_mode||'')}</p><p>检索 ${Number(q.timings?.retrieve||0).toFixed(1)} ms · 生成 ${Number(q.timings?.generate||0).toFixed(1)} ms · 候选 ${q.candidates.length}</p>${q.error?`<p class="error">${esc(q.error.error_code)} · ${esc(q.error.message)}</p>`:''}<details><summary>高级：候选与原始 JSON</summary><pre>${esc(JSON.stringify(q,null,2))}</pre></details></div>`}catch(e){toast(e.message)}};
