const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opt={}){const r=await fetch(url,opt);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error?.message||data.error?.error_code||data.detail?.message||data.detail?.code||data.detail||`HTTP ${r.status}`);return data}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3000)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')});
async function load(){try{const r=await api('/ready');$('#health').textContent=r.ready?'服务正常':'服务可用 · 组件待配置';$('#health').className='pill '+(r.ready?'ok':'bad')}catch{$('#health').textContent='服务离线';$('#health').className='pill bad'}const p=await api('/v1/papers');$('#scope').innerHTML=p.items.map(x=>`<option value="${x.paper_id}">${esc(x.file_name)}</option>`).join('');$('#paperList').innerHTML=p.items.map(x=>`<article class="card"><h3>${esc(x.file_name)}</h3><div class="status">${esc(x.status)}</div><p class="meta">${x.page_count} 页 · ${x.ocr_pages} OCR 页 · ${x.failed_pages.length} 失败页</p><button onclick="inspect('${x.paper_id}')">查看与复核</button>${['failed','partial_failed'].includes(x.status)?` <button onclick="retryPaper('${x.paper_id}')">安全重试</button>`:''}</article>`).join('')}
$('#askBtn').onclick=async()=>{const q=$('#question').value.trim();if(!q)return;$('#answer').innerHTML='<div class="panel">正在检索…</div>';try{const selected=[...$('#scope').selectedOptions].map(x=>x.value);const r=await api('/v1/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,paper_ids:selected.length?selected:null})});$('#answer').innerHTML=`${r.warnings.map(w=>`<div class="warning">${esc(w.message)} (${esc(w.code)})</div>`).join('')}<div class="panel"><p class="meta">${esc(r.answer_mode)} · ${r.timings_ms.total||r.timings_ms.retrieve} ms · ${esc(r.request_id)}</p><div class="answer-text">${esc(r.answer)}</div>${r.evidence.map(e=>`<div class="evidence"><b>${esc(e.paper_name)} · 第 ${e.page_start}${e.page_end!==e.page_start?'-'+e.page_end:''} 页</b><p>${esc(e.excerpt)}</p><span class="meta">${esc(e.evidence_id)} · ${esc(e.section_path)}</span><p><button onclick="reviewEvidence('${e.paper_id}',${e.page_start},'${e.chunk_id}')">回查原文</button></p></div>`).join('')}</div>`}catch(e){$('#answer').innerHTML=`<div class="warning">${esc(e.message)}</div>`}};
window.inspect=async id=>{try{const p=await api(`/v1/papers/${id}`);const c=await api(`/v1/papers/${id}/chunks?limit=20`);$('#inspect').classList.remove('hidden');$('#inspect').innerHTML=`<h3>${esc(p.file_name)}</h3><p><a href="/v1/papers/${id}/pdf" target="_blank">打开原始 PDF</a></p><h3>Chunks（前 20）</h3>${c.items.map(x=>`<details><summary>第 ${x.page_start}-${x.page_end} 页 · ${esc(x.section_path)} · ${x.token_count} tokens</summary><p>${esc(x.text)}</p><code>${x.chunk_id}</code></details>`).join('')}`;$('#inspect').scrollIntoView()}catch(e){toast(e.message)}};
$('#upload').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const r=await api('/v1/uploads',{method:'POST',headers:{'X-Filename':encodeURIComponent(f.name),'Content-Type':'application/pdf'},body:f});toast(r.run_id?`已创建任务 ${r.run_id}`:'相同论文已存在');if(r.run_id)$('#runId').value=r.run_id}catch(e){toast(e.message)}};
$('#runBtn').onclick=async()=>{try{$('#runResult').textContent=JSON.stringify(await api('/v1/runs/'+encodeURIComponent($('#runId').value.trim())),null,2)}catch(e){toast(e.message)}};
$('#loginBtn').onclick=async()=>{try{await api('/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});$('#loginState').textContent='已登录';toast('管理员登录成功')}catch(e){$('#loginState').textContent=e.message}};load();

$('#queryDiagBtn').onclick=async()=>{try{const id=$('#requestId').value.trim();const d=await api('/v1/queries/'+encodeURIComponent(id));$('#runResult').textContent=JSON.stringify(d,null,2)}catch(e){toast(e.message)}};
$('#runsBtn').onclick=async()=>{try{const r=await api('/v1/runs');$('#runsList').innerHTML=r.items.map(x=>`<article class="card"><b>${esc(x.status)}</b><p class="meta">${esc(x.run_id)}<br>${esc(x.stage||'queued')} · ${esc(x.started_at)}</p><button onclick="document.querySelector('#runId').value='${x.run_id}';document.querySelector('#runBtn').click()">查看阶段</button>${x.retryable_job&&['failed','partial_failed','interrupted'].includes(x.status)?` <button onclick="retryRun('${x.run_id}')">重试</button>`:''}</article>`).join('')}catch(e){toast(e.message)}};
window.retryRun=async id=>{try{const r=await api(`/v1/runs/${id}/retry`,{method:'POST'});toast(`已创建重试 ${r.run_id}`);$('#runsBtn').click()}catch(e){toast(e.message)}};
window.retryPaper=async id=>{try{const r=await api(`/v1/papers/${id}/retry`,{method:'POST'});toast(`已创建重试 ${r.run_id}`);$('#runId').value=r.run_id}catch(e){toast(e.message)}};
{const rawApi=api;api=async(url,opt={})=>{const data=await rawApi(url,opt);if(url==='/v1/query'&&data.request_id){$('#requestId').value=data.request_id;if(data.structured_extraction)setTimeout(()=>$('#answer').insertAdjacentHTML('beforeend',`<div class="panel"><h3>结构化抽取</h3><p class="meta">${esc(data.structured_extraction.extraction_run_id)} · ${esc(data.structured_extraction.schema_version)}</p>${data.structured_extraction.records.map(x=>`<p><b>${esc(x.field)}</b> ${esc(x.raw_value)} → ${esc(x.normalized_value)} ${esc(x.unit||'')} <span class="meta">${esc(x.evidence_id)}</span></p>`).join('')}</div>`),0)}return data}}
window.inspect=async id=>{try{const [p,pages,chunks]=await Promise.all([api(`/v1/papers/${id}`),api(`/v1/papers/${id}/pages`),api(`/v1/papers/${id}/chunks?limit=50`)]);$('#inspect').classList.remove('hidden');$('#inspect').innerHTML=`<h3>${esc(p.file_name)}</h3><p><a href="/v1/papers/${id}/pdf" target="_blank">打开原始 PDF</a></p><h3>页面解析</h3>${pages.items.map(x=>`<details data-page="${x.page_number}" class="${x.status==='failed'?'warning':''}"><summary>第 ${x.page_number} 页 · ${esc(x.extraction_method)} · ${esc(x.status)}${x.ocr_confidence!=null?' · OCR '+Number(x.ocr_confidence).toFixed(3):''}</summary>${x.error_code?`<p class="warning">${esc(x.error_code)} ${esc(x.error_message||'')}</p>`:''}<pre>${esc(x.text)}</pre></details>`).join('')}<h3>Chunks（前 50）</h3>${chunks.items.map(x=>`<details data-chunk="${x.chunk_id}"><summary>第 ${x.page_start}-${x.page_end} 页 · ${esc(x.section_path)} · ${x.token_count} tokens</summary><p>${esc(x.text)}</p><code>${x.chunk_id}</code><p class="meta">prev: ${esc(x.previous_chunk_id)} · next: ${esc(x.next_chunk_id)}</p></details>`).join('')}`;$('#inspect').scrollIntoView();return true}catch(e){toast(e.message);return false}};
window.reviewEvidence=async(id,page,chunk)=>{document.querySelector('button[data-view="papers"]').click();if(!await inspect(id))return;const target=document.querySelector(`#inspect [data-chunk="${chunk}"]`)||document.querySelector(`#inspect [data-page="${page}"]`);if(target){target.open=true;target.scrollIntoView({block:'center'});target.classList.add('review-target')}else toast('该证据不在当前复核分页中，请按页码打开原始 PDF')};
